const os = require('os');
const fs = require('fs');
const path = require('path');

/**
 * Script tự động tạo file .env với IP của máy
 * Chạy: node setup-env.js
 */

function getLocalIP() {
  const interfaces = os.networkInterfaces();

  // Ưu tiên WiFi và Ethernet
  const preferredNames = ['Wi-Fi', 'Ethernet', 'en0', 'eth0', 'wlan0'];

  // Thử tìm ở preferred interfaces trước
  for (const prefName of preferredNames) {
    if (interfaces[prefName]) {
      for (const iface of interfaces[prefName]) {
        if (iface.family === 'IPv4' && !iface.internal) {
          return iface.address;
        }
      }
    }
  }

  // Nếu không tìm thấy, quét tất cả
  for (const name of Object.keys(interfaces)) {
    for (const iface of interfaces[name]) {
      if (iface.family === 'IPv4' && !iface.internal) {
        return iface.address;
      }
    }
  }

  return 'localhost';
}

function createEnvFile() {
  const ip = getLocalIP();
  const envPath = path.join(__dirname, '.env');
  const envExamplePath = path.join(__dirname, '.env.example');
  const apiUrl = ip === 'localhost'
    ? 'http://localhost:4100/api'
    : `http://${ip}:4100/api`;

  console.log('\n╔════════════════════════════════════════════════════════╗');
  console.log('║       🚀 THIẾT LẬP CẤU HÌNH API TỰ ĐỘNG              ║');
  console.log('╚════════════════════════════════════════════════════════╝\n');

  // Backup file cũ nếu có
  if (fs.existsSync(envPath)) {
    const backupPath = `${envPath}.backup.${Date.now()}`;
    fs.copyFileSync(envPath, backupPath);
    console.log(`📦 Đã backup file .env cũ: ${path.basename(backupPath)}`);
  }

  const envContent = `# Auto-generated by setup-env.js
# Last updated: ${new Date().toLocaleString('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh' })}

# API Gateway URL - Auto-detected IP: ${ip}
EXPO_PUBLIC_API_GATEWAY_URL=${apiUrl}

# App Configuration
EXPO_PUBLIC_APP_NAME=HR Management System
EXPO_PUBLIC_APP_VERSION=1.0.0

# Environment
NODE_ENV=development

# ⚠️ LƯU Ý:
# - Nếu test trên điện thoại thật: Đảm bảo cùng mạng WiFi với máy tính
# - Nếu dùng Android Emulator: Có thể thay bằng http://10.0.2.2:4000/api
# - Nếu dùng iOS Simulator: Có thể thay bằng http://localhost:4000/api
`;

  fs.writeFileSync(envPath, envContent, 'utf8');

  // Tạo .env.example nếu chưa có
  if (!fs.existsSync(envExamplePath)) {
    const exampleContent = `# API Gateway URL
EXPO_PUBLIC_API_GATEWAY_URL=http://YOUR_IP_HERE:4100/api

# App Configuration
EXPO_PUBLIC_APP_NAME=HR Management System
EXPO_PUBLIC_APP_VERSION=1.0.0

# Environment
NODE_ENV=development
`;
    fs.writeFileSync(envExamplePath, exampleContent, 'utf8');
    console.log('✅ Đã tạo file .env.example');
  }

  console.log('✅ File .env đã được tạo thành công!\n');
  console.log('─'.repeat(56));
  console.log('📍 Thông tin cấu hình:');
  console.log('─'.repeat(56));
  console.log(`   IP máy tính: ${ip}`);
  console.log(`   API Gateway: ${apiUrl}`);
  console.log(`   File path:   ${envPath}\n`);

  console.log('─'.repeat(56));
  console.log('📱 Các bước tiếp theo:');
  console.log('─'.repeat(56));
  console.log('   1. Khởi động API Gateway:');
  console.log('      cd ../services/api-gateway && yarn dev\n');
  console.log('   2. Khởi động Mobile App:');
  console.log('      yarn start --clear\n');
  console.log('   3. Quét QR code bằng Expo Go app');
  console.log('   4. Đảm bảo điện thoại và máy tính cùng WiFi\n');

  console.log('─'.repeat(56));
  console.log('⚠️  Lưu ý quan trọng:');
  console.log('─'.repeat(56));
  console.log('   • Kiểm tra Firewall cho phép port 4100');
  console.log('   • API Gateway phải đang chạy trước');
  console.log('   • Nếu IP thay đổi, chạy lại: node setup-env.js\n');
}

// Chạy script
createEnvFile();
