"""khoi_tao_db_moi_5433

Revision ID: 0bb00ecc3399
Revises: 
Create Date: 2026-01-01 15:14:16.104812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '0bb00ecc3399'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure pgvector extension exists for vector column support
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('recognition_type', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('face_location', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_logs_id'), 'attendance_logs', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_logs_recognition_type'), 'attendance_logs', ['recognition_type'], unique=False)
    op.create_index(op.f('ix_attendance_logs_status'), 'attendance_logs', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_logs_timestamp'), 'attendance_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_attendance_logs_user_id'), 'attendance_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_attendance_logs_username'), 'attendance_logs', ['username'], unique=False)
    op.create_table('face_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('face_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_embeddings_id'), 'face_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_face_embeddings_is_active'), 'face_embeddings', ['is_active'], unique=False)
    op.create_index(op.f('ix_face_embeddings_user_id'), 'face_embeddings', ['user_id'], unique=False)
    op.create_index(op.f('ix_face_embeddings_username'), 'face_embeddings', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_face_embeddings_username'), table_name='face_embeddings')
    op.drop_index(op.f('ix_face_embeddings_user_id'), table_name='face_embeddings')
    op.drop_index(op.f('ix_face_embeddings_is_active'), table_name='face_embeddings')
    op.drop_index(op.f('ix_face_embeddings_id'), table_name='face_embeddings')
    op.drop_table('face_embeddings')
    op.drop_index(op.f('ix_attendance_logs_username'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_user_id'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_timestamp'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_status'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_recognition_type'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_id'), table_name='attendance_logs')
    op.drop_table('attendance_logs')
    # ### end Alembic commands ###

